# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 831)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectedProject = QtWidgets.QLabel(self.centralwidget)
        self.selectedProject.setGeometry(QtCore.QRect(250, 10, 431, 41))
        self.selectedProject.setObjectName("selectedProject")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(190, 0, 891, 781))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(260, 690, 311, 41))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 195, 781))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.robustnessBox = QtWidgets.QComboBox(self.widget_2)
        self.robustnessBox.setObjectName("robustnessBox")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.robustnessBox.addItem("")
        self.gridLayout_2.addWidget(self.robustnessBox, 3, 0, 1, 1)
        self.privacyBox = QtWidgets.QComboBox(self.widget_2)
        self.privacyBox.setObjectName("privacyBox")
        self.privacyBox.addItem("")
        self.privacyBox.addItem("")
        self.gridLayout_2.addWidget(self.privacyBox, 2, 0, 1, 1)
        self.effectivenessBox = QtWidgets.QComboBox(self.widget_2)
        self.effectivenessBox.setObjectName("effectivenessBox")
        self.effectivenessBox.addItem("")
        self.effectivenessBox.addItem("")
        self.gridLayout_2.addWidget(self.effectivenessBox, 1, 0, 1, 1)
        self.fairnessBox = QtWidgets.QComboBox(self.widget_2)
        self.fairnessBox.setObjectName("fairnessBox")
        self.fairnessBox.addItem("")
        self.fairnessBox.addItem("")
        self.gridLayout_2.addWidget(self.fairnessBox, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectedProject.setText(_translate("MainWindow", "This will show selected name"))
        self.pushButton.setText(_translate("MainWindow", "open tensorboard"))
        self.robustnessBox.setItemText(0, _translate("MainWindow", "Robustness"))
        self.robustnessBox.setItemText(1, _translate("MainWindow", "Backdoor Attacks"))
        self.robustnessBox.setItemText(2, _translate("MainWindow", "Data Poisoning Attacks"))
        self.robustnessBox.setItemText(3, _translate("MainWindow", "Model Poisoning Attacks"))
        self.robustnessBox.setItemText(4, _translate("MainWindow", "Byzantine Attacks"))
        self.robustnessBox.setItemText(5, _translate("MainWindow", "Free-rider Attacks"))
        self.robustnessBox.setItemText(6, _translate("MainWindow", "Inference Attacks"))
        self.robustnessBox.setItemText(7, _translate("MainWindow", "Byzantine Robustness"))
        self.robustnessBox.setItemText(8, _translate("MainWindow", "Sybil Robustness"))
        self.robustnessBox.setItemText(9, _translate("MainWindow", "Certified Robustness"))
        self.privacyBox.setItemText(0, _translate("MainWindow", "Privacy"))
        self.privacyBox.setItemText(1, _translate("MainWindow", "Inverting Gradients"))
        self.effectivenessBox.setItemText(0, _translate("MainWindow", "Effectivness"))
        self.effectivenessBox.setItemText(1, _translate("MainWindow", "Data-Free Knowledge"))
        self.fairnessBox.setItemText(0, _translate("MainWindow", "Fairness"))
        self.fairnessBox.setItemText(1, _translate("MainWindow", "Fair Averaging"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
